# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pybssm',
                'doc_host': 'https://michaelellis003.github.io',
                'git_url': 'https://github.com/michaelellis003/pybssm',
                'lib_path': 'pybssm'},
  'syms': {'pybssm.core': {'pybssm.core.foo': ('core.html#foo', 'pybssm/core.py')}}}